### ISSUE TITLE
Override the default controller

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbs2rest#12]
Having a internal default controller is useful but forcing it is bad. There should be a way to override the default controller for certain use cases.

Suggested UX:

```js
const myController = async (usecase, req, user, res, next, methodName) => {
...
}

const controllerList = [
  {
    name: 'lists',
    idParameter: 'listId',
    getAll: require('../usecases/getLists'), // default internal controller
    getById: { usecase: require('../usecases/getLists'), controller: myController }, // my controller
    ...
  }
]
```

**Comment by gabrielmellooliveira** [comment]
I created the customization for the controller and the addition of the name of the customized route parameter.

PR - https://github.com/herbsjs/herbs2rest/pull/11

**Comment by dalssoft** [comment]
great! tks!!
