### ISSUE TITLE
Handle Known Erros for better outputs

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbs2rest#17]
**Is your feature request related to a problem? Please describe.**
Improve [Known Errors](https://herbsjs.org/docs/usecase/result) support for use case return.

**Describe the solution you'd like**
Handle `Err.xxxx`, aka known erros, and return the proper HTTP status code.

**Comment by maikvortx** [comment]
Hi David, do you think defaultResolver should automatically interpret the error or should this be an option in the route settings?

**Comment by dalssoft** [comment]
If the use case return a `Ok` or a generic `Err` it should keep the current behavior. If it returns a Known Error, it should a proper HTTP status.

Given that I don't see the need for a extra option since this new behavior will not break the current clients.
