### ISSUE TITLE
ID field: use ID metadata from entity 

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbs2rest#21]
With the upcoming release of the "ID field" feature (https://github.com/herbsjs/gotu/issues/46), it would be possible to read the entity's metadata and, as a convention, use those IDs that today need to be explicitly defined.  

```js
const controllerList = [
  {
    name: 'lists',
    getAll: { usecase: require('../usecases/getLists'), controller: require('../controller') },
    getById: { usecase: require('../usecases/getLists'), id: 'listId' },       // <---- `id` would not be necessary
    post: { usecase: require('../usecases/createList') },
    put: { usecase: require('../usecases/updateList') },
    delete: { usecase: require('../usecases/deleteList') }
  }
]
```

Explicitly defining IDs would still be possible, but not mandatory for entities with IDs.

**Comment by italojs** [comment]
the discussion will continue into PR https://github.com/herbsjs/gotu/pull/57

**Comment by mtperesvx** [comment]
I can work on this issue.

**Comment by mtperesvx** [comment]
@dalssoft hi.
https://github.com/herbsjs/herbs2rest/pull/33#event-6888720180
