### ISSUE TITLE
Herbarium - Use metadata to customize REST endpoints

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbs2rest#28]
Dependency: https://github.com/herbsjs/herbs2rest/issues/22

Being able to customize REST endpoints is extremely important since the current convention is just one of many possible configurations.

But instead of informing the library (herbs2rest) explicitly how to behave, we should use generic metadata to achieve that.

For instance:

Verbs:
```js
herbarium.usecases.get('UpdateUser').metadata({ REST: { verb: 'GET' } })
```

URL path:
```js
herbarium.usecases.get('UpdateUser').metadata({ REST: { path: '/user/:id/update' } })
```

Resource:
```js
herbarium.usecases.get('UpdateUser').metadata({ REST: { resourceName: 'users' } })
```

**Comment by vitorgamer58** [comment]
What exactly does the resourceName field refer to?

**Comment by vitorgamer58** [comment]
> > What exactly does the resourceName field refer to?
> 
> The resource to be used: `GET /{resourceName}/` -> `GET /user/`

Would that make group replacement? Or addition?

For example, I have usecases and routes:
```
Test endpoints
    GET /Test/ -> ReadAll Usecase
    GET /Test/:id -> Read Usecase
    POST /Test -> Create Usecase
    PUT /Test/:id -> Update Usecase
    DELETE /Test/:id -> Delete Usecase
    OTHER /customgetallroute -> Other Usecase
```
If I pass the resourcename 'companies' it should look like this:
`PUT /Test/companies/:id -> Update Usecase`
Or
`PUT /companies/:id -> Update Usecase`
?

**Comment by dalssoft** [comment]
> Would that make group replacement? Or addition?

If you want to follow the convention `{httpVerb} /{resourceName}/:id` you can just inform `resourceName` and a path will be generated for you.

If you want to override the convention, you can inform the path directly. Ex: `/user/:id/update/foo/bla`.
