### ISSUE TITLE
Endpoints for non-CRUD use cases

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbs2rest#47]
What should be the behavior and convention for use cases that are not CRUD?

Ex:
`src\domain\usecases\user\removeAllUsersPermissions.js`
```js
module.exports = herbarium.usecases
    .add(removeAllUserPermissions, 'RemoveAllUserPermissions')
    .metadata({ group: 'User', operation: herbarium.crud.other, entity: User })
    .usecase
```

Currently herbs2rest doesn't recognize the operation and doen't generate the route. Developer must change `src\infra\api\rest\index.js` file in order to add the route:

```js
// Add custom controllers
controllers.push({
    name: 'RemoveAllPermissions',
    post: {
        usecase: herbarium.usecases.get('RemoveAllUserPermissions').usecase,
        controller: controller
    }
})
```

With this code the generated route is:
```js
POST /RemoveAllPermissions
```

However, I think that, with a few extra metadata, the use case should be recognized, the route should be generated automatically with a better route, respecting REST conventions.

Suggested code and behavior:

`src\domain\usecases\user\removeAllUsersPermissions.js`
```js
const removeAllUserPermissions = injection =>
    usecase('Remove all user permissions', {
        // Input/Request metadata and validation 
        request: {
            id: String
        },
    ...

module.exports = herbarium.usecases
    .add(removeAllUserPermissions, 'RemoveAllUserPermissions')
    .metadata({ group: 'User', operation: herbarium.crud.other })
    .usecase
```

`src\infra\api\rest\index.js`
```js
herbarium.usecases.get('RemoveAllUserPermissions').
    .metadata({
        REST: {
            group: 'User' // Endpoint group, optional. Default: usecase group
            delete:  '/User/:id/Permission', // Endpoint route with method and variable
            controller: controller 
        }
    })
```

```js
User endpoints
    GET /User -> Find all Users
    GET /User/:id -> Find a User
    POST /User -> Create User
    PUT /User/:id -> Update User
    DELETE /User/:id -> Delete User
    DELETE /User/:id/Permission -> Remove all user permissions
```

Related issue: https://github.com/herbsjs/herbs2rest/issues/28

**Comment by vitorgamer58** [comment]
Isn't it easier to pass like this?
```javascript
module.exports = herbarium.usecases
    .add(removeAllUserPermissions, 'RemoveAllUserPermissions')
    .metadata({ 
          group: 'User',
          operation: herbarium.crud.other,
          entity: User,
          REST: { path: '/updateAllUsers', verb: 'POST' } })
    .usecase
```

It would return like this in the console.

```
User endpoints
    GET /User/ -> Find all Users
    GET /User/:id -> Find a User
    POST /createuser -> Create User
    PUT /User/:id -> Update User
    DELETE /deleteuser/:id -> Delete User
    OTHER /deletealluser -> Delete all user
    OTHER /updateAllUsers -> Update User
```

So we have compatibility with the PR of customized endpoints, when the developer does not want an endpoint to be generated for the usecase, it would be enough not to pass the REST field.
Herbs2Rest will work with 'other' type usecases from lists, thus being able to have as many other endpoints as desired in a single entity, contrary to what is done today with standard verbs (get, post, put, delete) where we can only have one of each.

**Comment by dalssoft** [comment]
I didn't get it. I might have missed something but a few points:

`/deleteuser/` is not "RESTful", since it should be a resource name, like `/user/` or `/user/permission`, with no verb.

`DELETE /deleteuser/:id -> Delete User` -> This is not related to the use case `Remove all user permissions`

`OTHER DELETE /deletealluser -> Delete all user` -> (1) There is no `OTHER` http verb. (2) How it is related to `Remove all user permissions`?

`OTHER PUT /updateAllUsers -> Update User` -> Why `PUT` if it was `POST` on the metadata (`REST: { path: '/updateAllUsers', verb: 'POST' } })`)?
